### ISSUE TITLE
What is `order`?

### ISSUE THREAD

**Issue by goliney** [KenanYusuf/react-resplit#24]
I see the `order` prop in examples but I still don't fully understand its purpose. Could you please elaborate on that?

**Comment by kenanyusuf** [comment]
Hi @goliney

The order property specifies the order of the resplit child in the DOM (starts at 0, as it is essentially an index). A resplit child can be a pane or a splitter.

For example:
```tsx
<Resplit.Pane order={0} />
<Resplit.Splitter order={1} />
<Resplit.Pane order={2} />
<Resplit.Splitter order={3} />
<Resplit.Pane order={4} />
```

I will update the readme, but I would also like to find a way to remove this requirement when I have time.

**Comment by goliney** [comment]
Thank you for the response @KenanYusuf
