### ISSUE TITLE
Error: useResplitContext must be used within a ResplitRoot

### ISSUE THREAD

**Issue by TopVV** [KenanYusuf/react-resplit#25]
Hello,

I'm currently exploring the usage of the react-resplit library in my application. In the README, the example provided demonstrates the use of useResplitContext within a component. However, the example requires wrapping the component with <Resplit.Root> in the parent component.

Here's a snippet of the provided example:

```
import { Resplit, useResplitContext } from 'react-resplit';

function App() {
  const { isPaneCollapsed } = useResplitContext({
    direction: 'horizontal',
  });

  const handleResize = () => {
    if (isPaneCollapsed(2)) {
      // Do something
    }
  };

  return (
    <Resplit.Root>
      <Resplit.Pane order={0} initialSize="0.5fr">
        Pane 1
      </Resplit.Pane>
      <Resplit.Splitter order={1} size="10px" />
      <Resplit.Pane order={2} initialSize="0.5fr" onResize={handleResize}>
        Pane 2
      </Resplit.Pane>
    </Resplit.Root>
  );
}
```

[Sandbox with error for reference](https://codesandbox.io/p/sandbox/react-resplit-example-r7w6v2?file=%2Fsrc%2FApp.js)

I'm interested in finding a solution where I can encapsulate the use of react-resplit within a single component without relying on a parent component to provide <Resplit.Root>. While one approach could be creating a Higher Order Component (HOC), I'm curious if there are alternative methods or patterns that could achieve this while maintaining the library's functionality.

Any insights or suggestions would be greatly appreciated.

Thank you for your assistance!

**Comment by kenanyusuf** [comment]
Thanks for submitting the issue @TopVV - the context documentation was out of date. I have updated it now.

At the moment, the only way to use those methods is to render another component inside `Resplit.Root` that accesses resplit context. Check out this example https://github.com/KenanYusuf/react-resplit/blob/main/src/examples/Context.tsx

**Comment by TopVV** [comment]
Got it.
Thanks for the response
