### ISSUE TITLE
If `onResize`, `onResizeStart`, or `onResizeEnd` change, new values are ignored

### ISSUE THREAD

**Issue by jwalton** [KenanYusuf/react-resplit#32]
On the initial render of a pane, we call [registerPane()](https://github.com/KenanYusuf/react-resplit/blob/bc4de96e861c86f1bd8e42b42ce1aca7b66c7709/lib/Pane.tsx#L123-L133), passing in the various `onResize` handlers.  The problem is that if these functions change on a subsequent render, the updated functions will be ignored.  For example, I'm trying to keep track of whether or not one panel is "maximized":

```ts
    const { observe: refTopPane, height } = useDimensions();
    const isMaximized = height < 10;
    
    const onPaneResize =(size: FrValue) => {
        if (!isMaximized) {
            setPreviousSizes([size, `${1 - sizeNumber}fr`]); // Save current sizes
        }
    };
    
    ...
    
    <Resplit.Pane
                ref={refTopPane}
                onResizeEnd={onPaneResize}
            >    
```

But here `isMaximized` is always going to be false, because even though I pass in a new `onResizeEnd` handler every render, only the initial `onResizeEnd` is ever called.

A good way to work around this would be to store the `onResizeEnd` in a useRef inside of Pane. Something like:

```ts
    const onResizeEndRef = useRef(onResizeEnd);
    onResizeEndRef.current = onResizeEnd;
```

then pass this ref in to `registerPane()`.  The ref will be updated on every render, and whenever we need to call the callback we'll have access to the latest version.

**Comment by Lisa-Wall** [comment]
If this got fixed, we could remove our workaround. #upvote

**Comment by kenanyusuf** [comment]
Hi @jwalton @Lisa-Wall 

Thanks for logging the issue! Could you please try installing `v1.3.2-alpha.0` and see if that solves your issue?

**Comment by Lisa-Wall** [comment]
Hi @KenanYusuf, we tested this and it works! Thank you very much for fixing it. We were able to upgrade the library and remove our workaround.
